# Generated by Django 6.0.1 on 2026-01-14 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="城市名称"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="城市代码"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "城市",
                "verbose_name_plural": "城市",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DataCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="机房名称")),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="机房代码"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="地址"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_centers",
                        to="host_management.city",
                        verbose_name="所属城市",
                    ),
                ),
            ],
            options={
                "verbose_name": "机房",
                "verbose_name_plural": "机房",
                "ordering": ["city", "name"],
                "unique_together": {("city", "name")},
            },
        ),
        migrations.CreateModel(
            name="Host",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hostname",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="主机名"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        protocol="IPv4", verbose_name="IP地址"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "运行中"),
                            ("inactive", "已停止"),
                            ("maintenance", "维护中"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "os_type",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="操作系统类型",
                    ),
                ),
                ("cpu_cores", models.IntegerField(default=0, verbose_name="CPU核心数")),
                ("memory_gb", models.IntegerField(default=0, verbose_name="内存(GB)")),
                ("disk_gb", models.IntegerField(default=0, verbose_name="磁盘(GB)")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosts",
                        to="host_management.city",
                        verbose_name="所属城市",
                    ),
                ),
                (
                    "data_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosts",
                        to="host_management.datacenter",
                        verbose_name="所属机房",
                    ),
                ),
            ],
            options={
                "verbose_name": "主机",
                "verbose_name_plural": "主机",
                "ordering": ["hostname"],
            },
        ),
        migrations.CreateModel(
            name="HostPassword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("encrypted_password", models.TextField(verbose_name="加密后的密码")),
                (
                    "password_changed_at",
                    models.DateTimeField(auto_now=True, verbose_name="密码修改时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "host",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_record",
                        to="host_management.host",
                        verbose_name="主机",
                    ),
                ),
            ],
            options={
                "verbose_name": "主机密码",
                "verbose_name_plural": "主机密码",
            },
        ),
        migrations.CreateModel(
            name="RequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=500, verbose_name="请求路径")),
                ("method", models.CharField(max_length=10, verbose_name="请求方法")),
                ("status_code", models.IntegerField(verbose_name="状态码")),
                ("duration_ms", models.FloatField(verbose_name="耗时(毫秒)")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="客户端IP"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="User Agent"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "请求日志",
                "verbose_name_plural": "请求日志",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="host_manage_created_61dea0_idx"
                    ),
                    models.Index(
                        fields=["path", "method"], name="host_manage_path_9a147e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HostStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("host_count", models.IntegerField(default=0, verbose_name="主机数量")),
                (
                    "active_host_count",
                    models.IntegerField(default=0, verbose_name="运行中主机数量"),
                ),
                ("statistics_date", models.DateField(verbose_name="统计日期")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistics",
                        to="host_management.city",
                        verbose_name="城市",
                    ),
                ),
                (
                    "data_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistics",
                        to="host_management.datacenter",
                        verbose_name="机房",
                    ),
                ),
            ],
            options={
                "verbose_name": "主机统计",
                "verbose_name_plural": "主机统计",
                "ordering": ["-statistics_date", "city", "data_center"],
                "unique_together": {("city", "data_center", "statistics_date")},
            },
        ),
    ]
